name: species-id
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.12.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py37hf967b71_2
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - audioread=2.1.9=py37hf985489_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.3=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py37hf967b71_1001
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2020.12.5=h033912b_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2020.12.5=py38h50d1736_1
  - cffi=1.14.5=py37h4d371b4_0
  - chardet=4.0.0=py39h6e9494a_1
  - cryptography=3.4.7=py38h1fa4640_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=ha13b53f_2
  - decorator=5.0.6=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=he49afe7_0
  - ffmpeg=4.3.1=hb787a4c_2
  - fontconfig=2.13.1=hd23ceaa_1004
  - freetype=2.10.4=h4cff582_1
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.19.8.1=h7937167_1005
  - glib=2.68.1=he49afe7_0
  - glib-tools=2.68.1=he49afe7_0
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.37.0=py36h8d587b5_0
  - gst-plugins-base=1.18.4=h63a84d5_1
  - gstreamer=1.18.4=h8622b34_0
  - h5py=2.10.0=nompi_py38h9a16e60_106
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.10.0=py39h6e9494a_0
  - ipykernel=5.5.3=py38h6c79ece_0
  - ipython=7.22.0=py38h6c79ece_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py39h6e9494a_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py39h6e9494a_6
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37hf985489_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py36h615c93b_1
  - krb5=1.17.2=h60d9502_0
  - lame=3.100=h35c211d_1001
  - lcms2=2.12=h577c468_0
  - ld_impl_linux-64=2.35.1=h8edb8f9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang=11.1.0=default_he082bbe_0
  - libcurl=7.76.0=h8ef9fac_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=hddc9c9b_3
  - libffi=3.3=h046ec9c_2
  - libflac=1.3.3=h74dc148_1
  - libgfortran5=9.3.0=h6c81a4c_17
  - libglib=2.68.1=hd556434_0
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1=h009f743_3
  - libllvm11=11.1.0=hd011deb_2
  - libnghttp2=1.43.0=h07e645a_0
  - libogg=1.3.4=h35c211d_1
  - libopenblas=0.3.12=openmp_h63d9170_1
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.37=h7cec526_2
  - libpq=13.1=h052a64a_2
  - libprotobuf=3.15.7=hcf210ce_0
  - librosa=0.8.0=pyh9f0ad1d_0
  - libsndfile=1.0.31=he49afe7_1
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.2.0=h355d032_0
  - libuuid=2.32.1=h35c211d_1000
  - libvorbis=1.3.7=h046ec9c_0
  - libwebp-base=1.2.0=h0d85af4_2
  - libxcb=1.13=h35c211d_1003
  - libxml2=2.9.10=h802ca4f_3
  - llvmlite=0.36.0=py38h872f124_0
  - lz4-c=1.9.3=h046ec9c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py37hf967b71_3
  - matplotlib-base=3.4.1=py39hb07454d_0
  - mistune=0.8.4=py37hf967b71_1003
  - mysql-common=8.0.23=h694c41f_1
  - mysql-libs=8.0.23=h54f5a68_2
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=hedd7734_0
  - notebook=6.3.0=py37h5186d4c_0
  - nspr=4.30=hcd9eead_0
  - nss=3.63=h31e2bf1_0
  - numba=0.53.1=py38h8fd2267_0
  - numpy=1.20.2=py39h7eed0ac_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=hfd3ada9_0
  - openjpeg=2.4.0=h6cbf5cd_0
  - openssl=1.1.1k=h0d85af4_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py39h4d6be9b_0
  - pandoc=2.12=h0d85af4_0
  - pandocfilters=1.4.2=py36_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.44=h4a8c4bd_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38h83525de_1
  - pip=21.0.1=pyhd8ed1ab_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - prompt_toolkit=3.0.18=hd8ed1ab_0
  - protobuf=3.15.7=py39h9fcab8e_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h50d1736_7
  - pyqt-impl=5.12.3=py38h721a93c_7
  - pyqt5-sip=4.19.18=py38h5745d40_7
  - pyqtchart=5.12=py38h721a93c_7
  - pyqtwebengine=5.12.1=py38h721a93c_7
  - pyrsistent=0.17.3=py37hf967b71_2
  - pysocks=1.7.1=py38h50d1736_3
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.7.10=h7728216_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.0.3=py38hd3b92b6_1
  - qt=5.12.9=h126340a_4
  - qtconsole=5.0.3=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h0678c8f_2
  - requests=2.25.1=pyhd3deb0d_0
  - resampy=0.2.2=py_0
  - scikit-learn=0.24.1=py38hfd19401_0
  - scipy=1.6.2=py38h431c0a8_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h50d1736_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.35.4=h44b9ce1_0
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=h3cdfc77_0
  - tensorflow-base=1.14.0=mkl_py37h5a24fda_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - termcolor=1.1.0=py_2
  - terminado=0.9.4=py37hf985489_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py37hf967b71_1
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py37hf985489_4
  - wrapt=1.12.1=py36h20b66c6_3
  - x264=1!161.3030=h35c211d_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.5=h0b31af3_1
  - zeromq=4.3.4=h1c7c35f_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.9=h582d3a0_0
prefix: /home/jacob/miniconda3/envs/species-id

